apps/chat/urls.py
from django.urls import path

from apps.chat import views


app_name = "chat"


urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("room/<str:slug>/", views.ChatMessageView.as_view(), name="room"),
    path("messages/", views.stream_messages_view, name="stream-messages"),
]

apps/users/urls.py
from django.urls import path

from apps.users import views


app_name = "users"


urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("update-avatar/", views.UpdateAvatarView.as_view(), name="update_avatar"),
]

config/urls.py
import os

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from dotenv import load_dotenv


load = load_dotenv(settings.BASE_DIR / ".env")


urlpatterns = [
    path(f"{os.environ.get('ADMIN_URL', 'admin')}/", admin.site.urls),
    path("", include("apps.chat.urls")),
    path("auth/", include("apps.users.urls")),
    path("accounts/", include("allauth.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/chat/models.py
import json
from typing import Any, Dict, Tuple

from django.contrib.humanize.templatetags.humanize import naturaltime
from django.db import models
from django.template.defaultfilters import slugify

from apps.users.models import User


class Room(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True)
    icon = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        db_table = "rooms"

    def __str__(self) -> str:
        return self.name

    def save(self, *args: Tuple[Any, ...], **kwargs: Dict[str, Any]) -> None:
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class ChatMessage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name="messages")
    text = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "messages"

    def __str__(self) -> str:
        if len(self.text) > 10:
            return f"{self.user}: {self.text[:10]}..."
        else:
            return f"{self.user}: {self.text}"

    def as_json(self) -> str:
        return json.dumps(
            {
                "id": self.id,
                "slug": self.room.slug,
                "user": self.user.as_json(),
                "text": self.text,
                "created": str(naturaltime(self.created)),
            },
        )

apps/chat/views.py
import json
from collections.abc import AsyncGenerator
from typing import Union

import psycopg
from asgiref.sync import sync_to_async
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import connection
from django.http import (
    HttpRequest,
    HttpResponse,
    HttpResponseBadRequest,
    StreamingHttpResponse,
)
from django.shortcuts import get_object_or_404, render
from django.views import View

from apps.chat.models import ChatMessage, Room
from apps.chat.utils import sse_message, notify
from apps.users.models import Avatar


class IndexView(LoginRequiredMixin, View):
    def get(self, request: HttpRequest) -> HttpResponse:
        context = {
            "rooms": Room.objects.all(),
            "avatars": Avatar.objects.all(),
            "isAvatar": request.user.avatar is not None,
        }
        return render(request, "chat/index.html", context)


class ChatMessageView(LoginRequiredMixin, View):
    def get(self, request: HttpRequest, slug: str) -> HttpResponse:
        room = get_object_or_404(Room, slug=slug)
        context = {
            "cuurent_room": room,
            "rooms": Room.objects.all(),
            "messages": ChatMessage.objects.filter(room=room).all(),
            "avatars": Avatar.objects.all(),
            "isAvatar": request.user.avatar is not None,
        }
        return render(request, "chat/chat.html", context)

    def post(self, request: HttpRequest, slug: str) -> HttpResponse:
        room = get_object_or_404(Room, slug=slug)
        message = request.POST.get("message")
        if not message:
            return HttpResponseBadRequest("No message provided")
        message = ChatMessage.objects.create(user=request.user, room=room, text=message)
        notify(
            channel="lobby",
            event="message_created",
            event_id=message.id,
            data=message.as_json(),
        )
        return HttpResponse("OK")


async def stream_messages(last_id: Union[int, None] = None) -> AsyncGenerator[str, None]:
    connection_params = connection.get_connection_params()
    connection_params.pop("cursor_factory")

    aconnection = await psycopg.AsyncConnection.connect(
        **connection_params,
        autocommit=True,
    )
    channel_name = "lobby"

    if last_id:
        messages = ChatMessage.objects.filter(id__gt=last_id)
        async for message in messages:
            yield sse_message(
                event="message_created",
                event_id=message.id,
                data=sync_to_async(message.as_json)(),
            )

    async with aconnection.cursor() as acursor:
        await acursor.execute(f"LISTEN {channel_name}")
        gen = aconnection.notifies()
        async for notify_message in gen:
            payload = json.loads(notify_message.payload)
            event = payload.get("event")
            event_id = payload.get("event_id")
            data = payload.get("data")
            yield sse_message(
                event=event,
                event_id=event_id,
                data=data,
            )


async def stream_messages_view(request: HttpRequest) -> StreamingHttpResponse:
    last_id = request.headers.get("Last-Event-ID")
    return StreamingHttpResponse(
        streaming_content=stream_messages(last_id=last_id),
        content_type="text/event-stream",
    )

templates/chat/avatar.html
{% if not request.user.avatar %}
<style>
  input[type="radio"]:checked + label {
    background-color: #3B82F6;
  }
</style>
<div class="flex items-center justify-center h-screen w-screen bg-gray-100 absolute z-10">
  <form action="{% url 'users:update_avatar' %}" method="post" class="w-3/4 h-3/4 sm:w-full sm:h-full flex flex-col gap-4 justify-center items-center  rounded-lg">
    {% csrf_token %}
    <h1 class="text-2xl font-semibold mb-6 text-center">Select a avatar</h1>
    <div class="grid grid-cols-3 md:grid-cols-4 gap-8 p-4">
      {% for avatar in avatars %}
      <input id="avatar-{{ avatar.id }}" type="radio" name="avatar" value="{{ avatar.id }}" 
      {% if forloop.counter == 1 %}checked="checked"{% endif %} class="hidden">
      <label for="avatar-{{ avatar.id }}"
        class="flex justify-center items-center p-3 rounded-full  hover:bg-blue-300 cursor-pointer">
        <img src="{{ avatar.url }}" width="60" height="60" style="border-radius: 50%;">
      </label>
      {% endfor %}
    </div>
    <div class="flex justify-center items-center gap-4 w-80 mt-4">
      <button class="bg-blue-500 text-white px-4 py-2 rounded-md w-1/2">Apply</button>
    </div>
  </form>
</div>
{% endif %}

templates/chat/chat.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}


{% block content %}
{% include 'chat/sidebar.html' %}
{% include 'chat/avatar.html' %}

<!-- Main Content (Chat) -->
<div class="w-3/4">
  <div class="bg-white rounded-lg shadow-md h-screen">
    <div class="p-4 border-b border-gray-200">
      <h2 class="text-xl font-semibold">{{ cuurent_room }}</h2>
    </div>
    <div class="p-4 h-40 overflow-y-auto" style="height: 80%;" id="messages-container">
      {% for message in messages %}
        <div class="mb-4 rounded-md p-2 {% if message.user == request.user %}bg-blue-200{% else %}bg-gray-200{% endif %} flex flex-col">
          <div class="flex items-center mb-2 gap-4">
            <img src="{{ message.user.avatar.url }}" alt="avatar {{ message.user.name }}" width="40" height="40" style="border-radius: 50%;">
            <strong>{{ message.user.name }}</strong>
          </div>
          <p>{{ message.text }}</p>
          <small class="text-right text-gray-500 mt-2">{{ message.created|naturaltime }}</small>
        </div>
      {% endfor %}
    </div>

    <div class="p-4">
      <form class="flex" action="{% url 'chat:room' cuurent_room.slug %}" method="POST" id="new-message-form">
        {% csrf_token %}
        <input type="hidden" value="{% url 'chat:stream-messages' %}" id="streamURL">
        <input type="hidden" value="{% url 'chat:room' cuurent_room.slug %}" id="roomURL">
        <input type="text" class="w-full border rounded-md p-2 mr-2" placeholder="Type your message..." id="new-message" required>
        <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded-md">Send</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

{% block js %}
<input type="hidden" value="{{ request.user.publicId }}" id="userPublicID">
<script src="{% static 'chat/js/chat.js' %}"></script>
{% endblock %}

templates/chat/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
{% include 'chat/sidebar.html' %}
{% include 'chat/avatar.html' %}

<div class="w-3/4 flex flex-col gap-4 justify-center items-center relative">
  <img src="https://raw.githubusercontent.com/koolkishan/chat-app-react-nodejs/master/public/src/assets/robot.gif"
    alt="" width="300">
  <h1 class="text-2xl font-semibold mb-2">Welcome <span class="text-blue-500">{{ request.user.name }}</span>, to Chat App</h1>
  <strong>Select a room to start chatting</strong>
</div>

{% endblock %}

templates/chat/sidebar.html
<div class="bg-blue-500 text-white h-screen w-1/4 flex flex-col justify-between" style="min-width: 280px;">
  <div class="flex flex-col p-4 overflow-y-auto">
    <a href="{% url 'chat:index' %}">
      <h1 class="text-2xl font-semibold mb-6">Chat Rooms</h1>
    </a>
    <ul>
      {% for room in rooms %}
      <li class="mb-4">
        <a href="{% url 'chat:room' room.slug %}"
          class="flex items-center {% if room == cuurent_room %}bg-red-200 text-black{% endif %} hover:bg-gray-300 hover:text-black p-2 rounded"
          title="{{ room.name }}">
          <i class="fas fa-{{ room.icon }} mr-4"></i>
          {{ room.name }}
        </a>
      </li>
      {% endfor %}
    </ul>
  </div>
  <div class="flex items-center justify-between mb-2 p-4">
    <div class="flex items-center gap-4">
      <img src="{{ request.user.avatar.url }}" alt="{{ request.user.name }}" width="40" height="40"
        style="border-radius: 50%;">
      <strong>{{ request.user.name }}</strong>
    </div>
    <a href="{% url 'users:logout' %}" class="bg-blue-500 text-white"><i class="fa-solid fa-right-from-bracket"></i> Logout</a>
  </div>
</div>